import { IRepository } from '@/types'

export const PROJECTS: IRepository[] = [
  {
    id: 1,
    preview_img: '/media/projects/preview/lunar.png',
    img: '/media/projects/lunar.png',
    name: 'LunarCrush',
    description:
      'LunarCrush focuses on trading and provides information and insights about cryptocurrencies, stocks, and NFTs (Non-Fungible Tokens).',
    html_url: 'https://lunarcrush.com/',
    homepage: 'https://lunarcrush.com/',
    last_commit_at: '04/2022',
    languages: [
      { name: 'JavaScript', size: 78 },
      { name: 'PLSQL', size: 2 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'Redux',
      'JavaScript',
      'ECMAScript',
      'Tailwind',
      'D3',
      'AWS',
      'Docker',
      'Cypress',
      'Storybook',
      'Node.js',
      'SQL',
      'Github',
    ],
    role: 'Senior Frontend Engineer',
  },
  {
    id: 2,
    preview_img: '/media/projects/preview/jobscan.jpg',
    img: '/media/projects/jobscan.png',
    name: 'Jobscan',
    description:
      'Jobscan is web service that helps job seekers land more interviews by using AI to analyze one’s resume or LinkedIn profile against any job description.',
    html_url: 'https://jobscan.co/',
    homepage: 'https://jobscan.co/',
    last_commit_at: '04/2022',
    languages: [
      { name: 'JavaScript', size: 60 },
      { name: 'PHP', size: 18 },
      { name: 'PLSQL', size: 2 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['Vue.js', 'JavaScript', 'Laravel', 'SQL', 'Tailwind', 'Github'],
    role: 'Senior Frontend Engineer',
  },
  {
    id: 3,
    preview_img: '/media/projects/preview/cru.png',
    img: '/media/projects/cru.png',
    name: 'MPDX / Cru.org',
    description: 'An interdenominational Christian parachurch organization, 5k+ enterprise-sized company',
    html_url: 'https://next.mpdx.org/',
    homepage: 'https://next.mpdx.org/',
    last_commit_at: '09/2021',
    languages: [
      { name: 'TypeScript', size: 65 },
      { name: 'JavaScript', size: 20 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React.js',
      'TypeScript',
      'Next.js',
      'Apollo/GraphQL',
      'Material-UI',
      'Virtuoso',
      'Luxon',
      'Jest',
      'Storybook',
      'Okta',
      'Github',
    ],
    role: 'Senior Frontend Engineer',
  },
  {
    id: 4,
    preview_img: '/media/projects/preview/flux.jpg',
    img: '/media/projects/flux.jpg',
    name: 'Flux',
    description: 'Flux is all-inclusive vehicle subscription service in Malaysia.',
    html_url: 'https://driveflux.com/',
    homepage: 'https://driveflux.com/',
    last_commit_at: '02/2020',
    languages: [
      { name: 'JavaScript', size: 60 },
      { name: 'HTML', size: 10 },
      { name: 'Ruby', size: 20 },
      { name: 'PLSQL', size: 5 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'JavaScript',
      'Redux',
      'ECMAScript',
      'Next.js',
      'WhatsApp Business Chat',
      'Node.js',
      'Express.js',
      'Ruby',
      'SQL',
      'AWS',
      'Docker',
      'Github',
    ],
    role: 'Senior Full Stack Developer',
  },
  {
    id: 5,
    preview_img: '/media/projects/preview/moor.jpg',
    img: '/media/projects/moor.jpg',
    name: 'Moorhouse Coating',
    description: 'A professional painting contractor Serving the Southwest with roots in Park City, Utah, US',
    html_url: 'https://paintingproposal.com/',
    homepage: 'https://paintingproposal.com/',
    last_commit_at: '11/2018',
    languages: [
      { name: 'JavaScript', size: 50 },
      { name: 'Ruby', size: 28 },
      { name: 'PLSQL', size: 6 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
      { name: 'Kotlin', size: 1 },
    ],
    topics: [
      'React.js',
      'JavaScript',
      'Redux',
      'Lodash',
      'Formik',
      'Material-UI',
      'Highchart/ApexChart',
      'FullCalendar',
      'Node.js',
      'Express.js',
      'Ruby',
      'PostgreSQL',
      'Sequelize',
      'Auth0',
      'Stripe',
      'AWS',
      'Github',
    ],
    role: 'Full Stack Developer',
  },
  {
    id: 6,
    preview_img: '/media/projects/preview/workboard.jpg',
    img: '/media/projects/workboard.jpg',
    name: 'Workboard',
    description: 'An enterprise solution that can help employees make business decisions that align with strategic priorities',
    html_url: 'https://workboard.com/',
    homepage: 'https://workboard.com/',
    last_commit_at: '08/2017',
    languages: [
      { name: 'JavaScript', size: 83 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 7 },
    ],
    topics: ['React', 'JavaScript', 'Redux', 'Lodash', 'D3', 'Jest/Enzyme', 'Github'],
    role: 'Junior UI Engineeer',
  },
  {
    id: 7,
    preview_img: '/media/projects/preview/taskade.png',
    img: '/media/projects/taskade.png',
    name: 'Taskade',
    description: 'The unified collaboration hub for modern teams',
    html_url: 'https://taskade.com/',
    homepage: 'https://taskade.com/',
    last_commit_at: '07/2016',
    languages: [
      { name: 'JavaScript', size: 50 },
      { name: 'Ruby', size: 30 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'JavaScript',
      'Redux',
      'ECMAScript',
      'Node.js',
      'Express.js',
      'Ruby',
      'SQL',
      'AWS',
      'Docker',
      'Jest',
      'Storybook',
      'Github',
    ],
    role: 'Junior Full Stack Developer',
  },
]
