import { IRepository } from '@/types'

export const PROJECTS: IRepository[] = [
  {
    id: 1,
    preview_img: '/media/projects/preview/cxp.jpg',
    img: '/media/projects/cxp.jpg',
    name: 'Customer Experience Platform',
    description:
      'CXP is a light HRIS (Human Resource Information System) used by both internal and external users to manage worker jobs and associated information. It is integrated with various systems such as Okta for login, NetSuite for payroll and invoice payment, Salesforce for Onboarding creation, Looker for embedded reporting, and Pendo for analytics and Pendo Guides.',
    html_url: 'https://cloud.velocityglobal.com',
    homepage: 'https://cloud.velocityglobal.com',
    last_commit_at: '11/2018',
    languages: [
      { name: 'TypeScript', size: 40 },
      { name: 'JavaScript', size: 10 },
      { name: 'Elixir', size: 30 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
      { name: 'PLSQL', size: 5 },
    ],
    topics: [
      'React',
      'Redux',
      'TypeScript',
      'Material UI',
      'Tailwind',
      'Cypress',
      'Node',
      'Elixir',
      'PostgreSQL',
      'GraphQL',
      'Elasticsearch',
      'Docker',
      'Okta',
      'NetSuite',
      'Salesforce',
      'Pendo',
      'Looker',
      'AWS Lambda',
      'AWS S3',
    ],
    role: 'Senior Full Stack Developer',
  },
  {
    id: 2,
    preview_img: '/media/projects/preview/bookvid.jpg',
    img: '/media/projects/bookvid.jpg',
    name: 'Bookvid',
    description:
      'Bookvid is online meeting platform which provides group meeting or 1 to 1 booking sessions with features including real-time chat, donate, shopping, live streaming, recording, and so on.',
    html_url: 'https://bookvid.com',
    homepage: 'https://bookvid.com',
    last_commit_at: '07/2024',
    languages: [
      { name: 'TypeScript', size: 45 },
      { name: 'Python', size: 40 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'TypeScript',
      'React',
      'NextJS',
      'React Query',
      'Radix-UI',
      'Mantine',
      'Python',
      'Flask',
      'SQLAlchemy',
      'MySQL',
      'GCP',
      'Cronofy',
      'Stripe',
      'SendGrid',
      'Paypal',
    ],
    role: 'Tech Lead',
  },
  {
    id: 3,
    preview_img: '/media/projects/preview/relik.jpg',
    img: '/media/projects/relik.jpg',
    name: 'Relik',
    description:
      'Global social media application. Social media application which connects with celebrities and their followers through various of social platforms and components.',
    html_url: 'https://admin.relik.online',
    homepage: 'https://admin.relik.online',
    last_commit_at: '01/2024',
    languages: [
      { name: 'TypeScript', size: 70 },
      { name: 'JavaScript', size: 15 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'TypeScript',
      'React',
      'React Query',
      'Radix-UI',
      'Node',
      'NestJS',
      'Apollo/GraphQL',
      'MongoDB',
      'Matomo',
      'Jest',
      'Stripe',
      'AWS',
    ],
    role: 'Senior Frontend Engineer',
  },
  {
    id: 4,
    preview_img: '/media/projects/preview/renude.jpg',
    img: '/media/projects/renude.jpg',
    name: 'Renude',
    description:
      'Healthcare application which provides a simpler, smarter way to find custom skincare routines that work. Using face detecting AI mechanism to detect spots and disease on your face skin, and choose the right medicine or cosmetics to improve that.',
    html_url: 'https://renude.co',
    homepage: 'https://renude.co',
    last_commit_at: '04/2023',
    languages: [
      { name: 'TypeScript', size: 35 },
      { name: 'Python', size: 40 },
      { name: 'PLSQL', size: 10 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['TypeScript', 'React', 'NextJS', 'Tailwind', 'Python', 'Django', 'ML Principles', 'Stripe', 'Docker', 'AWS'],
    role: 'Senior Full Stack Developer',
  },
  {
    id: 5,
    preview_img: '/media/projects/preview/droneblocks.jpg',
    img: '/media/projects/droneblocks.jpg',
    name: 'Drone Blocks',
    description:
      'The site is about teaching computer science to children with Tello drones. Children can actually • develop a program that controls Tello drones using drag and drop editor.',
    html_url: 'https://droneblocks.io',
    homepage: 'https://droneblocks.io',
    last_commit_at: '08/2022',
    languages: [
      { name: 'TypeScript', size: 80 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'TypeScript',
      'React',
      'NextJS',
      'Tailwind',
      'ShadCN',
      'Node.js',
      'NestJS',
      'MongoDB',
      'Blockly',
      'Jest',
      'Storybook',
      'Stripe',
      'Mailtrap',
      'AWS',
    ],
    role: 'Senior Full Stack Developer',
  },
  {
    id: 6,
    preview_img: '/media/projects/preview/flux.jpg',
    img: '/media/projects/flux.jpg',
    name: 'DriveFlux',
    description:
      'The website is about lending cars and motorcycles in Malaysia. The basic idea behind the website was No need to buy a car when you can subscribe it.',
    html_url: 'https://driveflux.com/',
    homepage: 'https://driveflux.com/',
    last_commit_at: '02/2020',
    languages: [
      { name: 'TypeScript', size: 80 },
      { name: 'HTML', size: 10 },
      { name: 'PLSQL', size: 5 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React.js',
      'TypeScript',
      'Redux Toolkit/Saga',
      'styled-component',
      'SCSS',
      'NodeJS',
      'ExpressJS',
      'MongoDB',
      'GraphQL',
      'Stripe',
      'Mailjet',
      'AWS',
    ],
    role: 'Full Stack Developer',
  },
  {
    id: 7,
    preview_img: '/media/projects/preview/isluxury.jpg',
    img: '/media/projects/isluxury.jpg',
    name: 'Is Luxury',
    description:
      'LUXURY Estate Management, a division of IS LUXURY, is a full-service home management company specializing in the maintenance management of private luxury residences in premier luxury Las Vegas Valley communities. Their goal is to provide exceptional service to their property owners while maintaining a high standard of professionalism and integrity. I have developed the MVP in 6 months and now People in Las Vegas are actively using these services.',
    html_url: 'https://www.isluxury.com/',
    homepage: 'https://www.isluxury.com/',
    last_commit_at: '08/2019',
    languages: [
      { name: 'JavaScript', size: 40 },
      { name: 'PHP', size: 43 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 7 },
    ],
    topics: ['React', 'Redux', 'PHP', 'Laravel', 'Jest/Enzyme', 'MySQL', 'Sequelize'],
    role: 'Software Engineer',
  },
  {
    id: 8,
    preview_img: '/media/projects/preview/insomniacookies.png',
    img: '/media/projects/insomniacookies.png',
    name: 'insomniacookies',
    description: 'Café POS system that manages entire restaurant operations in a digitized manner',
    html_url: 'https://insomniacookies.com/',
    homepage: 'https://insomniacookies.com/',
    last_commit_at: '07/2017',
    languages: [
      { name: 'JavaScript', size: 50 },
      { name: 'Python', size: 30 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Node.js', 'Express', 'jQuery', 'Bootstrap', 'Python', 'PostgreSQL'],
    role: 'Software Engineer',
  },

  {
    id: 9,
    preview_img: '/media/projects/preview/turnup.jpg',
    img: '/media/projects/turnup.jpg',
    name: 'TurnUp',
    description:
      'Turnup is social media platform provides both web and mobile experience which enables people to create an daily events and invite people, manage posts and friends and so on.',
    html_url: 'https://turnupllc.tech/',
    homepage: 'https://turnupllc.tech/',
    last_commit_at: '10/2023',
    languages: [
      { name: 'PHP', size: 40 },
      { name: 'JavaScript', size: 35 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 10 },
    ],
    topics: ['PHP', 'Laravel', 'Flutter', 'MySQL', 'Mailgun', 'Paypal'],
    role: 'Full Stack Engineer',
  },
  {
    id: 10,
    preview_img: '/media/projects/preview/HygieneForAll.png',
    img: '/media/projects/HygieneForAll.png',
    name: 'HygieneForAll',
    description:
      'This application is developed for the product selling vendors and for customers. The vendor can register over the system to upload their product and to earn money from customers.',
    html_url: 'https://play.google.com/store/apps/details?id=com.hygieneliving',
    homepage: 'https://play.google.com/store/apps/details?id=com.hygieneliving',
    last_commit_at: '04/2018',
    languages: [
      { name: 'JavaScript', size: 50 },
      { name: 'PHP', size: 30 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['Android', 'iOS', 'PHP'],
    role: 'Software Engineer',
  },
  {
    id: 11,
    preview_img: '/media/projects/preview/StreeTak.png',
    img: '/media/projects/StreeTak.png',
    name: 'StreeTak',
    description:
      'The project is developed for the user to remember how to express your freedom and speak freely on the street, StreeTak is providing that same opportunity via a platform where all people can participate in a public conversation and speak freely and express their freedom of speech in safety without the fear of being “de-platformed, censured or bullied”.',
    html_url: 'https://apps.apple.com/in/app/streettak/id1586316028',
    homepage: 'https://apps.apple.com/in/app/streettak/id1586316028',
    last_commit_at: '09/2017',
    languages: [
      { name: 'JavaScript', size: 80 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 10 },
    ],
    topics: ['Android', 'iOS', 'Flutter', 'NodeJS'],
    role: 'Software Engineer',
  },
  {
    id: 12,
    preview_img: '/media/projects/preview/flymsg.png',
    img: '/media/projects/flymsg.png',
    name: 'FlyMSG',
    description: 'AI Writer & Autofill Text Expander App. Write, Expand, & Engage Everywhere!',
    html_url: 'https://chromewebstore.google.com/detail/flymsg-ai-writer-autofill/giidlnpcdhcldhfccdhkaicefhpokghc',
    homepage: 'https://chromewebstore.google.com/detail/flymsg-ai-writer-autofill/giidlnpcdhcldhfccdhkaicefhpokghc',
    last_commit_at: '04/2020',
    languages: [
      { name: 'TypeScript', size: 30 },
      { name: 'JavaScript', size: 30 },
      { name: 'PHP', size: 30 },
      { name: 'HTML', size: 5 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Angular', 'Laravel', 'AWS', 'ChatGPT'],
    role: 'Software Engineer',
  },
]
